spring:
  application:
    name: movie
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}/${DB_NAME:movie}?characterEncoding=UTF-8&serverTimezone=UTC
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:1234}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: ${JPA_SHOW_SQL:true}
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:create}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        naming:
          physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
        format_sql: ${JPA_FORMAT_SQL:false}
        highlight_sql: ${JPA_HIGHLIGHT_SQL:false}

logging:
  level:
    org.hibernate.SQL: ${LOGGING_LEVEL_SQL:DEBUG}  # 실행되는 SQL 로그 출력
    org.hibernate.orm.jdbc.bind: ${LOGGING_LEVEL_BIND:TRACE}  # SQL 바인딩된 파라미터 값 출력
